services:
  admin-nest-api:
    container_name: admin-nest-api
    image: admin-nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5002:5000
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - PG_HOST=admin-nest-db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=admin_db
      - PG_PORT=5432
    networks:
      - backend_network
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    depends_on:
      - admin-nest-db

  admin-nest-db:
    container_name: admin-nest-db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=admin_db
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - /data:/var/lib/postgresql/data

#  redis:
#    container_name: redis-db
#    image: redis
#    environment:
#      - REDIS_PORT=6379
#    ports:
#      - 6379:6379
#    networks:
#      - backend_network
#    restart: unless-stopped
#    volumes:
#      - redis:/data

networks:
  backend_network:
    driver: bridge
